services:
  gh-runner:
    build: .
    container_name: yolo-tracker-runner
    restart: always
    environment:
      GH_PAT: ${GH_PAT}             # langfristiger PAT
      GH_RUNNER_URL: https://github.com/wsv-2024/yolo-tracking-multi-image-linux
      GH_RUNNER_NAME: yolo-runner-2
      GH_RUNNER_WORKDIR: _work
      GH_RUNNER_LABELS: self-hosted,docker,linux
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
